config/routes.rb
Rails.application.routes.draw do
  resources :visitors, only: [:index, :show, :create] do
    resources :visitations, only: [:index]
  end

  root 'visitors#index'
end

app/models/visitor.rb
# == Schema Information
#
# Table name: visitors
#
#  id         :uuid             not null, primary key
#  email      :citext           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Visitor < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  has_many :visitations, dependent: :destroy

  scope :by_email, -> email { where('visitors.email ILIKE ?', "%#{ email }%" ) }

  accepts_nested_attributes_for :visitations, reject_if: :all_blank
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  protect_from_forgery with: :exception, except: [:create]

  before_action :set_visitor,  only: [:show]
  before_action :validate_api, only: [:create]

  has_scope :by_email

  # GET /visitors
  # GET /visitors.json
  def index
    @visitors = apply_scopes(Visitor.all)
                       .select(:id, :email, :created_at, :updated_at)
                       .order(:updated_at, :email)
                       .page(params[:page])

    respond_with @visitors do |format|
      format.html{ flash[:info] = I18n.t('simple_form.result', count: @visitors.count) }
      format.js
      format.json
    end
  end

  # GET /visitors/1
  # GET /visitors/1.json
  def show
    respond_with @visitor do |format|
      format.html
      format.json
    end
  end

  # POST /visitors
  # POST /visitors.json
  def create
    @visitor = Visitor.by_email(visitor_params[:email]).first

    if @visitor.present?
      @visitor.attributes = visitor_params
    else
      @visitor = Visitor.new(visitor_params)
    end

    respond_with @visitor, status: @visitor.save ? :created : :unprocessable_entity do |format|
      format.json{ render json: @visitor.to_json }
    end
  end

  private

    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    def visitor_params
      params.require(:visitor)
            .permit(:email, visitations_attributes: [ :id, :address, :time])
    end

    def validate_api
      return if ApiKey.exists?(key: params[:api_key])

      respond_with do |format|
        text = I18n.t('activerecord.errors.models.api_keys.key_not_found')
        format.json { render json: text, status: :unauthorized }
      end
    end
end

app/views/visitors/_filters.html.erb
<%= filter_form(visitors_path) do %>
  <%= label_tag( :email_filter, t('activerecord.attributes.visitor.email'), class: 'col-sm-1' ) %>
  <%= text_field_tag( :by_email, params[:by_email], placeholder: t('activerecord.attributes.visitor.email'), id: :by_email, class: 'col-sm-11' ) %>
<% end %>

app/views/visitors/_form.html.erb
<%= simple_form_for( @visitor ) do |form| %>
  <div class="form-inputs">
    <div class="col-sm-12 m-0 p-0">
      <%= form.input :email,      as: :string, required: true, disabled: true, wrapper_html: { class: 'col-sm-12' } %>
      <%= form.input :created_at, as: :date,   required: true, disabled: true, wrapper_html: { class: 'col-sm-6' } %>
      <%= form.input :updated_at, as: :date,   required: true, disabled: true, wrapper_html: { class: 'col-sm-6' }  %>
    </div>

    <div id="table-visitation" class="col-sm-12">
    </div>

    <div class="col-sm-12">
      <%= show_button( visitor_visitations_path(visitor_id: @visitor.id), 0,
                       t('activerecord.models.visitation', count: 2),
                       {text: t('simple_form.show', message: t('activerecord.models.visitation', count: 2)),
                        remote: true}) %>
    </div>
  </div>
<% end %>

app/views/visitors/_table.html.erb
<table id="data-table-command" data-toggle="bootgrid" class="table table-striped table-vmiddle bootgrid-table">
  <thead>
    <tr>
      <th data-column-id="email" data-identifier="true"><%= t('activerecord.attributes.visitor.email')      %></th>
      <th data-column-id="created_at"                  ><%= t('activerecord.attributes.visitor.created_at') %></th>
      <th data-column-id="updated_at"                  ><%= t('activerecord.attributes.visitor.updated_at') %></th>
    </tr>
  </thead>

  <tbody>
    <% @visitors.each do |visitor| %>
      <%= visitor_table_item(visitor) %>
    <% end %>
  </tbody>
</table>

<%= pagination_footer( @visitors ) %>

app/views/visitors/index.html.erb
<%= content_index(Visitor) do
  concat(render('filters'))
  concat(render('table'  ))
end %>

app/views/visitors/index.js.erb
$('#table-<%= Visitor.name.downcase%>').html('<%= escape_javascript render("table") %>');

app/views/visitors/show.html.erb
<%= regular_content( @visitor.email ) do %>
  <%= render( 'form' ) %>
<% end %>